version: 2.1
orbs:
  rust: circleci/rust@1.6.0
workflows:
  production:
    jobs:
      build:
        docker:
          - image: cimg/rust:1.61.0
        steps:
          - checkout
          - run: cargo test